import { Geist, Geist_Mono } from "next/font/google";
import Image from "next/image";

import { Button } from "@/components/button/Button";
import { Header } from "../components/header/Header";
import { Navigation } from "@/components/navigation/Navigation";
import { NavigationItem } from "@/components/navigation-item/NavigationItem";
import { UserProfile } from "@/components/userprofile/UserProfile";
import { Logo } from "@/components/logo/Logo";

import "./globals.css";

const geistSans = Geist({
  subsets: ["latin"],
  variable: "--font-geist-sans",
});

const geistMono = Geist_Mono({
  subsets: ["latin"],
  variable: "--font-geist-mono",
});

export const metadata = {
  description: "Generated by create next app",
  title: "Create Next App",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <Header>
          <Logo>
            <Image src="/taskflow-logo.svg" alt="Taskflow logo" fill={true} />
          </Logo>
          <div>
            <Button /> {/* Open / close button for mobile */}
          </div>
          <Navigation />
          <UserProfile />
        </Header>
        {children}
      </body>
    </html>
  );
}
