on: push

jobs:
  build:
    name: Lint and build application
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22"
          cache: npm

      - name: 🧰  Install
        run: npm ci --production-only

      - name: 🧹 Run lint
        run: npm run lint

      - name: 📦  build
        run: npm run build
